apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: pixelwise-dns
  namespace: pixelwise
spec:
  endpoints:
    - dnsName: pixelwise.tinyland.dev
      recordType: A
      targets:
        - 212.2.244.217
      recordTTL: 300
