apiVersion: v1
kind: Service
metadata:
  name: pixelwise
  namespace: pixelwise
  labels:
    app: pixelwise
spec:
  type: ClusterIP
  selector:
    app: pixelwise
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
